### ISSUE TITLE
Broken dependency

### ISSUE THREAD

**Issue by dmitry-meleshko** [use-go/onvif#1]
Looks like a broken dependency on https://github.com/yakovlevdmv/goonvif

..\xsd\built_in.go:14:2: cannot find package "github.com/yakovlevdmv/Golang-iso8601-duration" in any of:
        C:\Go\src\github.com\yakovlevdmv\Golang-iso8601-duration (from $GOROOT)

**Comment by crazybber** [comment]
fixed
