### ISSUE TITLE
why Authenticate function has been deleted?

### ISSUE THREAD

**Issue by felix-001** [use-go/onvif#26]
why Authenticate function has been deleted?

if GetAvailableDevicesAtSpecificEthernetInterface return devices, if the device need user/passwd, i can't use that device

i must need to use the device probed to newDevice

devices, err := goonvif.GetAvailableDevicesAtSpecificEthernetInterface("en7")
if err != nil {
      log.Println(err)
      return nil
}

for _, dev := range devices {
     newDev :=  onvif.NewDevice(onvif.DeviceParams{Xaddr: dev.params.Xaddr, Username: "username", Password: password})
}

**Comment by crazybber** [comment]
https://github.com/use-go/onvif/blob/master/examples/discovery_test.go#L24  check here ,if issue still ,you can Create a PR.
