### ISSUE TITLE
ptz / types / GetPresetsResponse - Profiles field should be a list

### ISSUE THREAD

**Issue by stefan-kiss** [use-go/onvif#30]
As the name implies we are expecting a list of profiles.
In fact in the onvif documentation we are also told we should expect a list.

RESPONSE:
• Preset - optional, unbounded [tt:PTZPreset]
List of presets for the requested MediaProfile.

Reference here: https://www.onvif.org/specs/srv/ptz/ONVIF-PTZ-Service-Spec.pdf

**Comment by jquiroga-arg** [comment]
Same Issue. Please merge to master
